name: Lint & Test PR

on:
  pull_request:
    branches: ['dev', 'master', 'next']

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: test-base
          MYSQL_USER: test-user
          MYSQL_PASSWORD: test-password
          MYSQL_ROOT_PASSWORD: root-password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: 3306
